<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:emails" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:emails">
<types>
<xsd:schema targetNamespace="urn:emails"
>
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
</xsd:schema>
</types>
<message name="enviarMailRequest">
  <part name="accion" type="xsd:integer" />
  <part name="params" type="xsd:Array" /></message>
<message name="enviarMailResponse">
  <part name="return" type="xsd:string" /></message>
<portType name="emailsPortType">
  <operation name="enviarMail">
    <documentation>Envio de emails</documentation>
    <input message="tns:enviarMailRequest"/>
    <output message="tns:enviarMailResponse"/>
  </operation>
</portType>
<binding name="emailsBinding" type="tns:emailsPortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="enviarMail">
    <soap:operation soapAction="urn:emails#enviarMail" style="rpc"/>
    <input><soap:body use="encoded" namespace="urn:emails" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
    <output><soap:body use="encoded" namespace="urn:emails" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>
<service name="emails">
  <port name="emailsPort" binding="tns:emailsBinding">
    <soap:address location="http://localhost/Jobbers/webservice/email.php"/>
  </port>
</service>
</definitions>